languages:
  -
    name: PHP
    key: php
    package_manager_install_command: composer install
  -
    name: Ruby
    key: ruby
    package_manager_install_command: bundle install --path vendor --binstubs
  -
    name: Javascript
    key: js
    package_manager_install_command: npm install

katas:
  -
    name: Fizz Buzz
    key: fizz_buzz
    requirements_file_path: katas/fizz_buzz.md
  -
    name: String Calculator
    key: string_calculator
    requirements_file_path: katas/string_calculator.md
  -
    name: Roman Numerals
    key: roman_numerals
    requirements_file_path: katas/roman_numerals.md

templates:
  -
    name: composer.json
    language: php
    template_src_path: templates/php/composer.json
    template_dest_path: composer.json
  -
    name: Gemfile
    language: ruby
    template_src_path: templates/ruby/Gemfile
    template_dest_path: Gemfile
  -
    name: package.json
    language: js
    template_src_path: templates/js/package.json
    template_dest_path: package.json
  -
    name: jasmine.json
    language: js
    template_src_path: templates/js/jasmine.json
    template_dest_path: spec/support/jasmine.json
